### PR TITLE
add basic build cicd

### PR DESCRIPTION
**Pull request by rudi-cilibrasi**
just an idea. to check PR and commits for buildability automatically each push.

here is an example of it working already
https://github.com/rudi-cilibrasi/hpc-now/actions/workflows/buildtest.yaml

### CODE REVIEW

**Comment by zhenrong-wang** [comment]
Thanks a lot, checking it now.

**Comment by rudi-cilibrasi** [comment]
and what did you see @zhenrong-wang?

**Comment by zhenrong-wang** [comment]
I was on a trip these days. Sorry for not responding. Will check it out by tomorrow.

**Comment by zhenrong-wang** [comment]
I have a question: This project is cross-platform, meaning that the binaries need to be built successfully on macOS, Windows, and Linux. Could that be done on GitHub using actions too? I saw the ci/cd you added is on ubuntu virtual environment.

**Comment by zhenrong-wang** [comment]
@rudi-cilibrasi

**Comment by rudi-cilibrasi** [comment]
yes @zhenrong-wang  you can do those tests also but i have not set them up myself on github so cannot help you with that as easily. linux came first and it is the only platform i routinely test on although i use many variations through docker images. find out more about Mac and Win here https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by zhenrong-wang** [comment]
@rudi-cilibrasi  I got the point. Let me have a try on Windows-latest and macos-latest. Github actions support these 2 OS.

**Pull request merged**
